### ISSUE TITLE
Quirky problems with comments 

### ISSUE THREAD

**Issue by jbreda007** [angryip/ipscan#180]
I have installed angry ip scanner on my linux mint 19.1 system and it works fine except:

1. when i add a comment then close and reopen ipscan the comments disappear but if I double click on an ip address then the comment appears again.

2. when I **rescan** from an open ipscan window I always get Java.lang.IndexOutOfBoundsException: index-1   out-of-bounds for length 0

**Comment by angryziber** [comment]
Comments are stored to the MAC address if it's available and to the IP adress otherwise. Can it be an issue that you scan with MAC fetcher first and then without?

Can you please provide the full stack trace of the IndexOutOfBoundsException from the terminal?

**Comment by lessharm** [comment]
Hello,
I have the same OS snd the same error described under 2, when I start a second scan. The second error occurs, when I nevertheless press the start-button after error 1 has occured. The only help for another scan til now is closing the program and reopen it (but then the same happens again). Thanks for your help ;)

Here is my terminal output from the program start to the errors:

ipscan
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.azib.ipscan.fetchers.HostnameFetcher (file:/usr/lib/ipscan/ipscan-linux64-3.5.5.jar) to field java.net.InetAddress.impl
WARNING: Please consider reporting this to the maintainers of net.azib.ipscan.fetchers.HostnameFetcher
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Apr. 13, 2019 1:46:15 NACHM. net.azib.ipscan.config.Labels get
WARNUNG: Used fallback label for button.ipUp
Apr. 13, 2019 1:46:15 NACHM. net.azib.ipscan.config.Labels get
WARNUNG: Used fallback label for button.ipUp
Apr. 13, 2019 1:46:15 NACHM. net.azib.ipscan.config.Labels get
WARNUNG: Used fallback label for menu.help.issues
Apr. 13, 2019 1:48:02 NACHM. net.azib.ipscan.Main getLocalizedMessage
SCHWERWIEGEND: unexpected error
java.lang.IndexOutOfBoundsException: Index -1 out-of-bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:440)
	at net.azib.ipscan.core.ScanningResultList.getResult(ScanningResultList.java:192)
	at net.azib.ipscan.gui.ResultTable$SetDataListener.handleEvent(ResultTable.java:229)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Table.checkData(Unknown Source)
	at org.eclipse.swt.widgets.Table.cellDataProc(Unknown Source)
	at org.eclipse.swt.widgets.Display.cellDataProc(Unknown Source)
	at org.eclipse.swt.internal.gtk.OS._gtk_list_store_clear(Native Method)
	at org.eclipse.swt.internal.gtk.OS.gtk_list_store_clear(Unknown Source)
	at org.eclipse.swt.widgets.Table.removeAll(Unknown Source)
	at net.azib.ipscan.gui.ResultTable.removeAll(ResultTable.java:195)
	at net.azib.ipscan.gui.actions.StartStopScanningAction.transitionTo(StartStopScanningAction.java:172)
	at net.azib.ipscan.core.state.StateMachine.notifyAboutTransition(StateMachine.java:85)
	at net.azib.ipscan.gui.SWTAwareStateMachine.access$001(SWTAwareStateMachine.java:24)
	at net.azib.ipscan.gui.SWTAwareStateMachine$1.run(SWTAwareStateMachine.java:39)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at net.azib.ipscan.Main.main(Main.java:74)

Apr. 13, 2019 1:49:11 NACHM. net.azib.ipscan.Main getLocalizedMessage
SCHWERWIEGEND: unexpected error
java.lang.IllegalThreadStateException
	at java.base/java.lang.Thread.start(Thread.java:804)
	at net.azib.ipscan.gui.actions.StartStopScanningAction.transitionTo(StartStopScanningAction.java:198)
	at net.azib.ipscan.core.state.StateMachine.notifyAboutTransition(StateMachine.java:85)
	at net.azib.ipscan.gui.SWTAwareStateMachine.access$001(SWTAwareStateMachine.java:24)
	at net.azib.ipscan.gui.SWTAwareStateMachine$1.run(SWTAwareStateMachine.java:39)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at net.azib.ipscan.Main.main(Main.java:74)

**Comment by lessharm** [comment]
Hello angryziber,

thank you very much by solving this issue with the 3.6-version!

**Comment by turcotronics** [comment]
Hello,
Angry IP Scanner 3.7.0, Xubuntu 18.04.0
Comment not shown on scan, but it appears on double clicking.
Thanks,
Rodolfo

**Comment by turcotronics** [comment]
> Hello,
> Angry IP Scanner 3.7.0, Xubuntu 18.04.0
> Comment not shown on scan, but it appears on double clicking.
> Thanks,
> Rodolfo

SOLVED: MAC address column must be shown before COMMENT column but near the last columns otherwise few MAC addresses are shown :-)

**Comment by MacPaKKo** [comment]
Same problem on Version 3.7.2 Windows 10 (and also on previous 3.6.x)
Comments not shown on scan, but they appears on double clicking individually.

The TRICK to avoid the bug is to move the comments column to the right of MAC column, so they'll be shown instantly on ip detection

**Comment by angryziber** [comment]
Lots of comment fixes in 3.8.2
