### ISSUE TITLE
Unable to launch due to "org.eclipse.swt.SWTError: No more handles"

### ISSUE THREAD

**Issue by Hobbit44** [angryip/ipscan#217]
OS Ubuntu 19.10
Installed x64 deb package

```
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.graphics.Cursor.<init>(Unknown Source)
	at org.eclipse.swt.widgets.Display.getSystemCursor(Unknown Source)
	at net.azib.ipscan.gui.MainWindow.createToolbarButton(MainWindow.java:183)
	at net.azib.ipscan.gui.MainWindow.initControlsArea(MainWindow.java:166)
	at net.azib.ipscan.gui.MainWindow.<init>(MainWindow.java:76)
	at net.azib.ipscan.config.DaggerMainComponent.createMainWindow(DaggerMainComponent.java:748)
	at net.azib.ipscan.Main.main(Main.java:71)
```

**Comment by angryziber** [comment]
It works perfectly for me on Ubuntu 19.10, Xorg session. Are you using Wayland or any non-standard theme or display manager?

Basically, it seems that SWT cannot be initialized while reading your cursor theme.

Gdk-Message: 10:05:51.263: Unable to load hand2 from the cursor theme

This seems to be related:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=526357

**Comment by Hobbit44** [comment]
Its trying to launch on wayland but it was initially installed on Unity. I have tried uninstalling and reinstalling but to no avail. 

Is there any leftover assets i need to delete manually?

**Comment by angryziber** [comment]
It seems the workaround is to use XOrg session, not Wayland

**Comment by MaxG-Enpal** [comment]
Anything new on this issue?
