### ISSUE TITLE
please remove crash related to hard requirement on GoogleAnalytics

### ISSUE THREAD

**Issue by chrisdlangton** [angryip/ipscan#262]
GoogleAnalytics is causing the program to crash because all google domains are blocked in several client environments 

```
Sep 30, 2020 1:05:49 AM net.azib.ipscan.util.GoogleAnalytics report
WARNING: Failed to report
java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:240)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246)
	at net.azib.ipscan.util.GoogleAnalytics.report(GoogleAnalytics.java:33)
	at net.azib.ipscan.util.GoogleAnalytics.report(GoogleAnalytics.java:52)
	at net.azib.ipscan.Main.handleFatalError(Main.java:82)
	at net.azib.ipscan.Main.main(Main.java:76)
```

This is an issue because, specifically, all our customers (100+) use a transparent squid proxy as a NAT gateway in AWS, which allows only whitelisted egress. It is pretty common, and basically a standard in corporate networks (even average security professionals have dns blackholed google on home networks these days).

Consider making this optional - in fact all your tracking and egress that is not a target (`-f:` argument) should be removed - it's not very professional to do that and i'm actually a bit shocked you think security minded users would put up with that kind of thing

**Comment by angryziber** [comment]
I understand your concern and that's why there is a checkbox when you first start the app to disable crash and upgrade reports to Google Analytics. You can access it any time later by pressing F1.

But, if reporting doesn't work, it just outputs a warning, but should continue to work normally. Does it really crash in your case?

**Comment by angryziber** [comment]
No reporting will be performed anymore if you are using any command-line options (for automation).

However, any crashes will still be tried to be reported unless you opt-out in the F1/Getting Started dialog.
If reporting fails, nothing will be output by default.
