### ISSUE TITLE
SEVERE: Unable to create pinger: pinger.icmp

### ISSUE THREAD

**Issue by magixus** [angryip/ipscan#272]
**Describe the bug**
Cannot ping with ICMP pinger

**To Reproduce**
1. Open angry IP Scanner
2. Choose your network 
3. clique on the right setting icon beside 'IP RANGE'
4. choose ICMP echo on `pinging => pinging method`
5. Click OK

**Expected behavior**

IPSCAN to show alive hosts  with ICMP pinger

**Screenshots**
this message is shown 
![image](https://user-images.githubusercontent.com/7642058/104853243-d053f500-58ff-11eb-94a4-734099b11465.png)

and on CLI : 
![image](https://user-images.githubusercontent.com/7642058/104853251-dc3fb700-58ff-11eb-86f4-75be9059e8b5.png)

**Versions (please complete the following information):**
 - OS :
 ```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
```
 - Java version, 32 or 64 bit, how was installed (`java -version`)
  ```
  openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-120.04, mixed mode, sharing)
```

 - Version of Angry IP Scanner
 ``` 3.7.3
 build Date  : 2020-10-27```

**Logs:**
- Please run Angry IP Scanner from command-line and see if any relevant logs were written. Paste them here.
```
Jan 17, 2021 8:08:34 PM net.azib.ipscan.core.net.PingerRegistry createPinger
SEVERE: Unable to create pinger: pinger.icmp
java.io.IOException: Operation not permitted
	at org.savarese.rocksaw.net.RawSocket.__throwIOException(RawSocket.java:176)
	at org.savarese.rocksaw.net.RawSocket.open(RawSocket.java:228)
	at net.azib.ipscan.core.net.ICMPSharedPinger.<init>(ICMPSharedPinger.java:52)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at net.azib.ipscan.core.net.PingerRegistry.createPinger(PingerRegistry.java:69)
	at net.azib.ipscan.core.net.PingerRegistry.checkSelectedPinger(PingerRegistry.java:86)
	at net.azib.ipscan.gui.PreferencesDialog.savePreferences(PreferencesDialog.java:408)
	at net.azib.ipscan.gui.PreferencesDialog.access$000(PreferencesDialog.java:33)
	at net.azib.ipscan.gui.PreferencesDialog$1.widgetSelected(PreferencesDialog.java:117)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5745)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5013)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4507)
	at net.azib.ipscan.gui.AbstractModalDialog.open(AbstractModalDialog.java:47)
	at net.azib.ipscan.gui.PreferencesDialog.openTab(PreferencesDialog.java:94)
	at net.azib.ipscan.gui.PreferencesDialog.open(PreferencesDialog.java:75)
	at net.azib.ipscan.gui.actions.ToolsActions$Preferences.handleEvent(ToolsActions.java:46)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5745)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5013)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4507)
	at net.azib.ipscan.gui.GUI.showMainWindow(GUI.java:51)
	at net.azib.ipscan.Main.main(Main.java:60)

Jan 17, 2021 8:08:34 PM net.azib.ipscan.core.net.PingerRegistry checkSelectedPinger
INFO: ICMP pinger failed: net.azib.ipscan.fetchers.FetcherException: pingerCreateFailure
```

**Comment by JonnyTech** [comment]
The message suggested running with root privileges (ie `sudo ipscan`), did you do so?

**Comment by angryziber** [comment]
Yes, please run ipscan as root, e.g. `sudo ipscan`, then ICMP pinger will be selected automatically.
On Linux, sending ICMP packets is not allowed for unprivileged users by default.
