### ISSUE TITLE
Undocumented runtime dependency? "Could not load SWT library"

### ISSUE THREAD

**Issue by lestephane** [angryip/ipscan#289]
**Describe the bug**
Getting an error on startup on a fresh install of Ubuntu 20.04 + openjdk. It's a missing JWT dependency, that is neither documented in the README nor the Debian control file.

**To Reproduce**
- fresh Ubuntu 20.04 install
- `apt install default-jdk`
- `dpkg -i ipscan_3.7.6_amd64.deb`
```
Selecting previously unselected package ipscan.
(Reading database ... 220101 files and directories currently installed.)
Preparing to unpack ipscan_3.7.6_amd64.deb ...
Unpacking ipscan (3.7.6) ...
Setting up ipscan (3.7.6) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
```
- launch ipscan
- error (see screenshot, and logs section)

**Expected behavior**
- the debian package installation step should fail because of an unsatisfied SWT library dependency.
  the debian control file looks incomplete: `Depends: DEPENDS java8-runtime` (this is not sufficient)
- a hint should be included in the error message (or this project's README) as to what the JWT dependency
  to install is called for the operating system I'm running on.

**Screenshots**
![image](https://user-images.githubusercontent.com/5460884/115507324-a30f3e00-a284-11eb-95a6-f603c013114f.png)

**Versions (please complete the following information):**
 - OS type and version: 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - Java version, 32 or 64 bit, how was installed (`java -version`):
 ```
 $ java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```
installed with `apt-get install default-jdk`
 - Version of Angry IP Scanner: 3.7.6

**Logs:**
```
$ ipscan 
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-gtk-4940r23 in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
	no swt-gtk in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
	Can't load library: /home/lestephane/libswt-gtk-4940r23-64.so
	Can't load library: /home/lestephane/libswt-gtk-64.so

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:338)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:257)
	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:209)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:155)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:163)
	at net.azib.ipscan.gui.GUI.<init>(GUI.java:29)
	at net.azib.ipscan.Main.main(Main.java:47)
```

**Comment by angryziber** [comment]
I guess you mean SWT (Standard Widget Toolkit), not JWT.
Actually, if you install amd64 version, it has the correct SWT bundled - it extracts it automatically from the jar file (you can look inside of ipscan.jar and see it).

There's another story with the "all" arch deb file - this one requires you to provide your own swt, and it's in the debian control file:
```
Depends: libswt-gtk-4-java, libswt-cairo-gtk-4-jni, java8-runtime
```
You can try this one and see if it works for you.

Both work on my Ubuntu 21.04 and have worked on 20.04 as well before...

**Comment by angryziber** [comment]
I have checked: the extracted swt libraries should be put here on Linux, do you see these files?
```
$ ls ~/.swt/lib/linux/x86_64
libswt-atk-gtk-4940r23.so    libswt-gtk-4940r23.so
libswt-cairo-gtk-4940r23.so  libswt-pi3-gtk-4940r23.so
```

**Comment by lestephane** [comment]
> I guess you mean SWT (Standard Widget Toolkit), not JWT.

oops yes.

>  the extracted swt libraries should be put here on Linux, do you see these files?

Ah. My home directory is write protected, exactly for this reason, because the top level dot directory and file namespace becomes too bloated over time, and I want to specifically allow each and every one of them.

So I guess, what is missing is a better error message when the .so files can't be extracted to ~/.swt.

I'll use the "all" arch deb file in the meantime. But I'm happy to test any fix to the error reporting if someone takes a stab at it.

**Comment by angryziber** [comment]
This is an issue in SWT library itself from the Eclipse project, please report to https://bugs.eclipse.org/bugs/
