### ISSUE TITLE
Failed to run. Windows

### ISSUE THREAD

**Issue by Ygarr** [angryip/ipscan#369]
Win10
```
java -version
openjdk version "18.0.1.1" 2022-04-22
OpenJDK Runtime Environment (build 18.0.1.1+2)
OpenJDK 64-Bit Server VM (build 18.0.1.1+2, mixed mode, sharing)
```

```
 java -jar .\ipscan-any-3.8.2.jar
java.lang.NoClassDefFoundError: org/eclipse/swt/SWTError
        at net.azib.ipscan.Main.main(Main.java:50)
Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.SWTError
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 1 more
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/swt/SWTError
        at net.azib.ipscan.util.GoogleAnalytics.extractFirstStackFrame(GoogleAnalytics.java:69)
        at net.azib.ipscan.util.GoogleAnalytics.report(GoogleAnalytics.java:54)
        at net.azib.ipscan.Main.main(Main.java:83)
Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.SWTError
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 3 more
```

**Comment by angryziber** [comment]
ipscan-any-3.8.2.jar will work on Linux only, such as Raspberry Pi.

Please use Windows builds to run on Windows.
