### ISSUE TITLE
arcolinux terminal

### ISSUE THREAD

**Issue by klein-de** [angryip/ipscan#379]
arcolinux ipscan installed with package manager, it runs and works fine with the exception fetchers, when you try to run wakeonline it does not open a terminal, it either doesn't like the terminals installed or the one it is looking for isn't installed , what terminal does it require? i depend heavily on wakeonlan, vncviewer, ssh, sftp, all run when put in terminal just not ipscan fetchers.

**Comment by angryziber** [comment]
You can easily find from the source code the terminals that are tried:
https://github.com/angryip/ipscan/blob/master/src/net/azib/ipscan/gui/actions/TerminalLauncher.java#L68

Current list is:
"x-terminal-emulator", "xdg-terminal", "gnome-terminal", "xfce4-terminal", "konsole", "xterm"

Which one do you have?

**Comment by klein-de** [comment]
xfce4-terminal  1.0.4  &  xterm are installed 

Angry IP Scanner]
Version: 3.8.2
Build date: 2022-01-22

[klein@aspire-arco-openbox ~]$ ipscan
Dec 10, 2022 2:14:18 PM net.azib.ipscan.fetchers.HostnameFetcher <clinit>
WARNING: Could not get InetAddressImpl
java.lang.reflect.InaccessibleObjectException: Unable to make field static final java.net.InetAddressImpl java.net.InetAddress.impl accessible: module java.base does not "opens java.net" to unnamed module @543c6f6d
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
	at net.azib.ipscan.fetchers.HostnameFetcher.<clinit>(HostnameFetcher.java:37)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:201)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:547)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:497)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at net.azib.ipscan.di.Injector.createInstance(Injector.java:41)
	at net.azib.ipscan.di.Injector.require(Injector.java:24)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at net.azib.ipscan.di.Injector.register(Injector.java:29)
	at net.azib.ipscan.config.ComponentRegistry.register(ComponentRegistry.java:23)
	at net.azib.ipscan.config.ComponentRegistry.init(ComponentRegistry.java:38)
	at net.azib.ipscan.config.ComponentRegistry.init(ComponentRegistry.java:32)
	at net.azib.ipscan.Main.main(Main.java:57)



ipscan even when you tell it to open a terminal in the fetcher window it does not. like wol and you tick the box to have it run in terminal it does not open a terminal but it does run the program wakeonlan .

wakeonlan ${fetcher.mac}   <= works
vncviewer ${fetcher.ip}   <= works
thunar Sftp://${fetcher.hostname}/   <= works
ssh ${fetcher.ip}  <= don't work

i can't figure it out  first time i'v ever had a problem with ipscan .

wish.list
would be nice to be able to pass a text file to ipscan when it is started .
like a list of previously scanned itp's.

id just be happy to get ssh working .

**Comment by angryziber** [comment]
OK, I have realised that `xfce4-terminal` uses a different execute arg (-x), fixing it

**Comment by angryziber** [comment]
> would be nice to be able to pass a text file to ipscan when it is started .

Please use `ipscan -f:file file.txt` for that

**Comment by klein-de** [comment]
ipscan -f:file file.txt does not work as i would like,  ipscan tries to run  the text file where i would just like the contents displayed, so i can use the fetchers on what ever line to start a computer, ssh into one after it is started, etc.....
example of my .txt  file .
Generated by Angry IP Scanner 3.7.0
https://angryip.org

Scanned 192.168.1.0 - 192.168.1.255
Nov 27, 2020, 9:07:03 PM

IP              Ping            Hostname                			MAC Address      
192.168.1.1     1 ms            house_DD-WRT            			18:xx:C7:6D:58:50
192.168.1.2     0 ms            shop_DD-WRT				00:1C:xx:BE:44:DD
192.168.1.3     0 ms            dinning_DD-WRT				00:xx:10:BE:44:DD
192.168.1.6     0 ms            008-SERVER              			00:15:xx:F2:0A:69
192.168.1.7     0 ms            dv97-002.local          			00:xx:E1:42:2E:55
192.168.1.8     0 ms            shop-755.local          			00:1C:xx:BE:44:DD
192.168.1.10    0 ms            DELL-001-270            			00:xx:B9:1A:BA:C6
192.168.1.11    0 ms            DELL-002-270            			00:0D:xx:21:EC:47
192.168.1.12    0 ms            DELL-001-GX280          		00:12:3F:xx:89:8F

ipscan tries to fine each computer, where they aren't in most cases not running till i wakeonlan with a fetcher.
