### ISSUE TITLE
AngryIP Scanner freezing in Win10

### ISSUE THREAD

**Issue by GoingOutWest** [angryip/ipscan#450]
**Describe the bug**
When attempting to change settings or interact with the program it freezes, requiring a system reboot to close the program. .

**To Reproduce**
1. Go to 'open porgram'
2. Click on 'Gear icon for settings'
3. program freezes, must reboot to close window

**Expected behavior**
Program to open setting dialog.

**Screenshots**

**Versions (please copy from the About dialog or complete manually):**
 - 3.9.1 
 - Win10, Dell Latitude5421
 - Java version, vendor (`java -version`) - or if Windows installer was used with bundled Java
 
**Logs:**
- Please run Angry IP Scanner from Terminal and see if any relevant logs were written. Paste them here:
  - Windows: `jre\bin\java -jar ipscan.exe` (inside of installation directory, e.g. C:\Program Files\Angry IP Scanner)
  - Mac: `Angry\ IP\ Scanner.app/Contents/MacOS/ipscan`
  - Linux: `ipscan` or `java -jar ipscan.jar`

  - C:\Program Files\Angry IP Scanner>jre\bin\java -jar ipscan.exe
Jun 07, 2024 9:30:33 AM net.azib.ipscan.fetchers.HostnameFetcher <clinit>
WARNING: Could not get InetAddressImpl
java.lang.reflect.InaccessibleObjectException: Unable to make field static final java.net.InetAddressImpl java.net.InetAddress.impl accessible: module java.base does not "opens java.net" to unnamed module @3632be31
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.Field.setAccessible(Unknown Source)
        at net.azib.ipscan.fetchers.HostnameFetcher.<clinit>(HostnameFetcher.java:37)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at net.azib.ipscan.di.Injector.createInstance(Injector.java:41)
        at net.azib.ipscan.di.Injector.require(Injector.java:24)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at net.azib.ipscan.di.Injector.register(Injector.java:29)
        at net.azib.ipscan.config.ComponentRegistry.register(ComponentRegistry.java:20)
        at net.azib.ipscan.config.ComponentRegistry.init(ComponentRegistry.java:35)
        at net.azib.ipscan.config.ComponentRegistry.init(ComponentRegistry.java:29)
        at net.azib.ipscan.Main.main(Main.java:57)

**Comment by themaiz** [comment]
I have seen the same problem.   I believe I have tracked it down to a dialogue window opening, but off the screen.   For instance, at the end of a scan, a popup appears with scan stats.  If that window can't be found, then clicking on the main AngryIP window results in the Windows "ding".  Annoyingly, at that point AngryIP cannot be killed from the taskmanager, and even though attempting a kill or end process tree looks to have worked, the main AngryIP window does not close and cannot be managed.

I suspect the situation occurs is a result of a stored value that positions the popup outside the boundaries of physical screens, where it can't be seen at all.  Cascading windows, closing windows, and scrolling through windows does not find the popup.

The only way I have found to clear this situation is to reboot (fixes most things, but is really inconvenient) or play find-the-popup.  And the only way I've been able to find it is to disconnect all additional screens so that all windows appear on my laptop screen, and then set the laptop screen to 4k.  

When I found the popup hiding in one corner of the 4k screen, I moved it back to the top left, resized the screen to 1920, and then dismissed the popup and closed AngryIP.  That seems to have rewritten good coordinates for the popup.
