### ISSUE TITLE
Fails to Terminate all Threads

### ISSUE THREAD

**Issue by tgaguy** [angryip/ipscan#457]
**Describe the bug**
when scanning a range of ip's. ie 10.2.30.0 - 10.2.30.255. shows all threads then counts down as they terminate but fail to continue and sticks as 46 remaining. Only stopping manually produces results. Scan will wait infinitely for threads to terminate. Consistent network activity during this 46 threads remaining time. Network activity reduces significantly when manually stopped. Connected via Lan cable. Not connected to wifi. 

Watching the ethernat status 

**To Reproduce**
Steps to reproduce the behavior: Run a  scan 

**Expected behavior**
All treads to terminate and produce results

**Screenshots**
![2024-08-29 (3)](https://github.com/user-attachments/assets/ea8a832f-3aef-4176-b3fa-65ce913e1c4c)
![2024-08-29 (2)](https://github.com/user-attachments/assets/847f9a55-7838-423a-afad-a38b0b0707c4)
![2024-08-29 (7)](https://github.com/user-attachments/assets/dbd3ce6f-c42a-4e23-ac97-dbc2d2a37927)
![2024-08-29 (6)](https://github.com/user-attachments/assets/4b16bbce-c3f3-43ac-a7ca-faea80751f69)
![2024-08-29 (5)](https://github.com/user-attachments/assets/b713354b-7d92-498b-a76e-aa4883b54d20)

**Versions (please copy from the About dialog or complete manually):**
 - Version of Angry IP Scanner 
 - OS, version, CPU architecture
 - Java version, vendor (`java -version`) - or if Windows installer was used with bundled Java

Version: 3.9.1
Build date: 2023-02-11 
- Java: BellSoft 17.0.6+10-LTS
OS: Windows 11 10.0 (amd64)
SWT: win32 4956
 
**Logs:**
- Please run Angry IP Scanner from Terminal and see if any relevant logs were written. Paste them here:
  - Windows: `jre\bin\java -jar ipscan.exe` (inside of installation directory, e.g. C:\Program Files\Angry IP Scanner)
  - Mac: `Angry\ IP\ Scanner.app/Contents/MacOS/ipscan`
  - Linux: `ipscan` or `java -jar ipscan.jar`

PS C:\Program Files\Angry IP Scanner> jre\bin\java -jar ipscan.exe
Aug 29, 2024 10:30:50 AM net.azib.ipscan.fetchers.HostnameFetcher <clinit>
WARNING: Could not get InetAddressImpl
java.lang.reflect.InaccessibleObjectException: Unable to make field static final java.net.InetAddressImpl java.net.InetAddress.impl accessible: module java.base does not "opens java.net" to unnamed module @527740a2
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.Field.setAccessible(Unknown Source)
        at net.azib.ipscan.fetchers.HostnameFetcher.<clinit>(HostnameFetcher.java:37)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at net.azib.ipscan.di.Injector.createInstance(Injector.java:41)
        at net.azib.ipscan.di.Injector.require(Injector.java:24)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at net.azib.ipscan.di.Injector.register(Injector.java:29)
        at net.azib.ipscan.config.ComponentRegistry.register(ComponentRegistry.java:20)
        at net.azib.ipscan.config.ComponentRegistry.init(ComponentRegistry.java:35)
        at net.azib.ipscan.config.ComponentRegistry.init(ComponentRegistry.java:29)
        at net.azib.ipscan.Main.main(Main.java:57)

Aug 29, 2024 10:30:50 AM net.azib.ipscan.gui.actions.HelpMenuActions$CheckVersion$1 run
WARNING: null
java.net.UnknownHostException: angryip.org
        at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
        at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
        at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at net.azib.ipscan.gui.actions.HelpMenuActions$CheckVersion$1.run(HelpMenuActions.java:120)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Northern666** [comment]
Same issue here.

**Comment by angryziber** [comment]
This issue has been resolved. The thread hang during scanning was caused by a resource leak (UDP sockets not being closed on exception in `HostnameFetcher`/`MDNSResolver`/`NetBIOSResolver`) and stale active fetcher entries in `Scanner`. These resource leaks and exception handling issues have now been fixed.
